language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - echo "no tests to run yet"
deploy:
  provider: gae
  keyfile: secure/client-secret.json
  project: pryce-cs467
before_install:
- openssl aes-256-cbc -K $encrypted_2869a6f1dd15_key -iv $encrypted_2869a6f1dd15_iv
  -in secure/client-secret.json.enc -out secure/client-secret.json -d
