runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

  # should encrypt these later
env_variables:
  SQLALCHEMY_DATABASE_URI: postgres+pg8000://postgres:rnYs8GThytvG8auG@/pryce_db?unix_sock=/cloudsql/pryce-cs467:us-central1:pryce-postgres/.s.PGSQL.5432