"""empty message

Revision ID: 1000e1061553
Revises: 72e301ad1550
Create Date: 2020-02-10 06:55:16.018174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1000e1061553'
down_revision = '72e301ad1550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appuser', sa.Column('lat', sa.Numeric(precision=17, scale=15), nullable=True))
    op.add_column('appuser', sa.Column('lng', sa.Numeric(precision=18, scale=15), nullable=True))
    op.drop_column('appuser', 'home')
    op.alter_column('price', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.add_column('store', sa.Column('lat', sa.Numeric(precision=17, scale=15), nullable=True))
    op.add_column('store', sa.Column('lng', sa.Numeric(precision=18, scale=15), nullable=True))
    op.add_column('store', sa.Column('reported', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'reported')
    op.drop_column('store', 'lng')
    op.drop_column('store', 'lat')
    op.alter_column('price', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.add_column('appuser', sa.Column('home', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('appuser', 'lng')
    op.drop_column('appuser', 'lat')
    # ### end Alembic commands ###
