"""Removing duplicate FK on pryce_list_item.pryce_list_id

Revision ID: 239ad2155f59
Revises: c827ee4a1745
Create Date: 2020-02-20 18:16:46.430144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239ad2155f59'
down_revision = 'c827ee4a1745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pryce_list_item_pryce_list_id_fkey', 'pryce_list_item', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pryce_list_item_pryce_list_id_fkey', 'pryce_list_item', 'pryce_list', ['pryce_list_id'], ['pryce_list_id'])
    # ### end Alembic commands ###
