"""adding name to list model

Revision ID: 41277ca11f79
Revises: bacf2d9c86f2
Create Date: 2020-02-14 09:35:07.263656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41277ca11f79'
down_revision = 'bacf2d9c86f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'name')
    # ### end Alembic commands ###
