"""Adding fk to comment for store"

Revision ID: 4f418a639089
Revises: c75b9013d2bb
Create Date: 2020-02-23 19:43:02.008088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f418a639089'
down_revision = 'c75b9013d2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'store', ['store_id'], ['store_id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'store_id')
    # ### end Alembic commands ###
