"""empty message

Revision ID: 576964f4fe91
Revises: ed1846c2a4ad
Create Date: 2020-02-04 22:39:17.412169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import FetchedValue

revision = '576964f4fe91'
down_revision = 'ed1846c2a4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('uri', sa.String(), nullable=True))
    op.drop_constraint('image_fspath_key', 'image', type_='unique')
    op.create_unique_constraint(None, 'image', ['uri'])
    op.drop_column('image', 'fspath')
    op.add_column('item', sa.Column('quant_unit', sa.String(), server_default=FetchedValue(), nullable=True))
    op.add_column('item', sa.Column('quantity', sa.Numeric(), nullable=True))
    op.drop_column('item', 'weight_unit')
    op.drop_column('item', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('weight', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('weight_unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('item', 'quantity')
    op.drop_column('item', 'quant_unit')
    op.add_column('image', sa.Column('fspath', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image', type_='unique')
    op.create_unique_constraint('image_fspath_key', 'image', ['fspath'])
    op.drop_column('image', 'uri')
    # ### end Alembic commands ###
