"""empty message

Revision ID: 6ff1853017d1
Revises: 54179a03702e
Create Date: 2020-02-06 00:47:07.348968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff1853017d1'
down_revision = '54179a03702e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'store', ['place_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='unique')
    # ### end Alembic commands ###
