"""empty message

Revision ID: 81a8e22e3e49
Revises: 7bc6eb79e09b
Create Date: 2020-01-31 05:35:45.823703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a8e22e3e49'
down_revision = '7bc6eb79e09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'weight',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'weight',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
