"""Modifying Comment model to be specifically geared toward items

Revision ID: 89822cb9c72b
Revises: 239ad2155f59
Create Date: 2020-02-20 21:56:50.819086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89822cb9c72b'
down_revision = '239ad2155f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_id', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'item', ['item_id'], ['item_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_column('comment', 'type')
    op.drop_column('comment', 'object_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comment', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'item_id')
    op.drop_column('comment', 'comment_id')
    # ### end Alembic commands ###
