"""empty message

Revision ID: c0f27eaaed09
Revises: c87f5fe41f62
Create Date: 2020-02-24 22:07:53.746481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f27eaaed09'
down_revision = 'c87f5fe41f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('appuser_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(content IS NOT NULL) OR (rating IS NOT NULL)', name='comment_check'),
    sa.ForeignKeyConstraint(['appuser_id'], ['appuser.appuser_id'], name='comment_appuser_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], name='comment_item_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['store.store_id'], name='comment_store_id_fkey', onupdate='CASCADE', ondelete='RESTRICT')
    )
    # ### end Alembic commands ###
