"""renaming list to pryce_list

Revision ID: c827ee4a1745
Revises: 41277ca11f79
Create Date: 2020-02-14 11:27:19.808120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import ProgrammingError
from sqlalchemy.schema import FetchedValue

# revision identifiers, used by Alembic.
revision = 'c827ee4a1745'
down_revision = '41277ca11f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pryce_list',
    sa.Column('pryce_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('access_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['access_id'], ['access.access_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner'], ['appuser.appuser_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pryce_list_id')
    )
    op.create_table('pryce_list_item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('pryce_list_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=FetchedValue(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pryce_list_id'], ['pryce_list.pryce_list_id'], ),
    sa.ForeignKeyConstraint(['pryce_list_id'], ['pryce_list.pryce_list_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('item_id', 'pryce_list_id')
    )
    op.drop_constraint('list_item_item_id_fkey', 'list_item', type_='foreignkey'),
    op.drop_constraint('list_item_list_id_fkey', 'list_item', type_='foreignkey'),
    op.drop_table('list_item')
    op.drop_constraint('list_access_id_fkey', 'list', type_='foreignkey')
    op.drop_constraint('list_owner_fkey', 'list', type_='foreignkey')
    op.drop_table('list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('list_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['access_id'], ['access.access_id'], name='list_access_id_fkey',
                        onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner'], ['appuser.appuser_id'], name='list_owner_fkey',
                        onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('list_id', name='list_pkey')
    )
    op.create_table('list_item',
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], name='list_item_item_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['list_id'], ['list.list_id'], name='list_item_list_id_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('item_id', 'list_id', name='list_item_pkey')
    )

    op.drop_table('pryce_list_item')
    op.drop_table('pryce_list')
    # ### end Alembic commands ###
