"""empty message

Revision ID: c87f5fe41f62
Revises: 4f418a639089
Create Date: 2020-02-24 21:48:11.176026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87f5fe41f62'
down_revision = '4f418a639089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'rating',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'rating',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
