"""empty message

Revision ID: e5c7d01e68d1
Revises: 81a8e22e3e49
Create Date: 2020-02-02 17:16:06.803606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5c7d01e68d1'
down_revision = '81a8e22e3e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'price')
    op.drop_column('price', 'reported')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('reported', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('price', sa.Column('price', postgresql.MONEY(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
