"""empty message

Revision ID: ed1846c2a4ad
Revises: e5c7d01e68d1
Create Date: 2020-02-02 17:16:45.206426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1846c2a4ad'
down_revision = 'e5c7d01e68d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('price', sa.Numeric(), nullable=True))
    op.add_column('price', sa.Column('reported', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'reported')
    op.drop_column('price', 'price')
    # ### end Alembic commands ###
